# Cloudflare Pages configuration for KhoAugment POS Frontend
name = "kho1"
compatibility_date = "2024-07-14"

# Pages-specific configuration
pages_build_output_dir = "dist"

# Environment variables for production
[env.production.vars]
VITE_API_URL = "https://kho1-api-production.bangachieu2.workers.dev"
VITE_APP_ENV = "production"
VITE_APP_NAME = "KhoAugment POS"
VITE_APP_VERSION = "1.0.0"
VITE_BASE_URL = "https://kho1.pages.dev"
VITE_VNPAY_RETURN_URL = "https://kho1.pages.dev/payment/vnpay/return"
VITE_MOMO_RETURN_URL = "https://kho1.pages.dev/payment/momo/return"
VITE_ZALOPAY_RETURN_URL = "https://kho1.pages.dev/payment/zalopay/return"
VITE_ENABLE_PWA = "true"
VITE_ENABLE_ANALYTICS = "true"
VITE_ENABLE_ERROR_TRACKING = "true"
VITE_CACHE_VERSION = "v1"
VITE_OFFLINE_SUPPORT = "true"

# Environment variables for preview
[env.preview.vars]
VITE_API_URL = "https://kho1-api-preview.bangachieu2.workers.dev"
VITE_APP_ENV = "preview"
VITE_BASE_URL = "https://preview.kho1.pages.dev"