# Cloudflare Configuration for KhoAugment POS
# Enhanced deployment configuration for production-ready deployment

name = "khoaugment-pos"
main = "backend/src/index.ts"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

# Development environment
[env.development]
name = "khoaugment-pos-dev"
vars = { ENVIRONMENT = "development" }

# Staging environment  
[env.staging]
name = "khoaugment-pos-staging"
vars = { ENVIRONMENT = "staging" }

# Production environment
[env.production]
name = "khoaugment-pos-prod"
vars = { ENVIRONMENT = "production" }

# Worker configuration
workers_dev = true
route = ""
zone_name = ""

# Durable Objects
[[durable_objects.bindings]]
name = "SESSIONS"
class_name = "SessionStorage"
script_name = "khoaugment-pos"

[[durable_objects.bindings]]
name = "RATE_LIMITER"
class_name = "RateLimiter"
script_name = "khoaugment-pos"

# KV Namespaces
[[kv_namespaces]]
binding = "CACHE"
id = "your-cache-namespace-id"
preview_id = "your-cache-preview-id"

[[kv_namespaces]]
binding = "SETTINGS"
id = "your-settings-namespace-id"
preview_id = "your-settings-preview-id"

# R2 Buckets
[[r2_buckets]]
binding = "UPLOADS"
bucket_name = "khoaugment-uploads"
preview_bucket_name = "khoaugment-uploads-preview"

[[r2_buckets]]
binding = "BACKUPS"
bucket_name = "khoaugment-backups"
preview_bucket_name = "khoaugment-backups-preview"

# D1 Databases
[[d1_databases]]
binding = "DB"
database_name = "khoaugment-pos-db"
database_id = "your-database-id"

[[d1_databases]]
binding = "ANALYTICS_DB"
database_name = "khoaugment-analytics-db"
database_id = "your-analytics-database-id"

# Queue Bindings
[[queues.consumers]]
queue = "payment-processing"
max_batch_size = 10
max_batch_timeout = 30
max_retries = 3
dead_letter_queue = "payment-dlq"

[[queues.consumers]]
queue = "email-notifications"
max_batch_size = 5
max_batch_timeout = 10
max_retries = 3

[[queues.consumers]]
queue = "audit-logs"
max_batch_size = 20
max_batch_timeout = 60
max_retries = 2

[[queues.producers]]
binding = "PAYMENT_QUEUE"
queue = "payment-processing"

[[queues.producers]]
binding = "EMAIL_QUEUE"
queue = "email-notifications"

[[queues.producers]]
binding = "AUDIT_QUEUE"
queue = "audit-logs"

# Analytics Engine
[[analytics_engine_datasets]]
binding = "ANALYTICS"

# Vectorize
[[vectorize]]
binding = "SEARCH_INDEX"
index_name = "product-search"

# Environment Variables
[vars]
# Application
APP_NAME = "KhoAugment POS"
APP_VERSION = "2.1.0"
NODE_ENV = "production"

# API Configuration
API_BASE_URL = "https://api.khoaugment.com"
FRONTEND_URL = "https://pos.khoaugment.com"
CORS_ORIGINS = "https://pos.khoaugment.com,https://admin.khoaugment.com"

# Security
JWT_ALGORITHM = "HS256"
JWT_EXPIRES_IN = "24h"
REFRESH_TOKEN_EXPIRES_IN = "7d"
BCRYPT_ROUNDS = "12"
RATE_LIMIT_WINDOW = "900000"
RATE_LIMIT_MAX = "100"

# Vietnamese Business
TIMEZONE = "Asia/Ho_Chi_Minh"
CURRENCY = "VND"
LOCALE = "vi-VN"
DEFAULT_VAT_RATE = "0.10"
BUSINESS_LICENSE_REQUIRED = "true"

# Payment Gateways
VNPAY_VERSION = "2.1.0"
VNPAY_COMMAND = "pay"
VNPAY_CURRENCY_CODE = "VND"
MOMO_PARTNER_CODE = "MOMOBKUN20180529"
ZALOPAY_APP_ID = "2553"

# Cache Settings
CACHE_TTL = "3600"
REDIS_TTL = "7200"
CDN_CACHE_TTL = "86400"

# Upload Settings
MAX_FILE_SIZE = "10485760"
ALLOWED_FILE_TYPES = "image/jpeg,image/png,image/webp,application/pdf"
UPLOAD_PATH = "/uploads"

# Monitoring
LOG_LEVEL = "info"
ENABLE_ANALYTICS = "true"
ENABLE_ERROR_TRACKING = "true"
PERFORMANCE_MONITORING = "true"

# Feature Flags
ENABLE_BARCODE_SCANNING = "true"
ENABLE_RECEIPT_PRINTING = "true"
ENABLE_LOYALTY_PROGRAM = "true"
ENABLE_INVENTORY_ALERTS = "true"
ENABLE_MULTI_LOCATION = "true"
ENABLE_ADVANCED_REPORTING = "true"

# Development/Staging specific vars
[env.development.vars]
NODE_ENV = "development"
LOG_LEVEL = "debug"
API_BASE_URL = "https://dev-api.khoaugment.com"
FRONTEND_URL = "https://dev.pos.khoaugment.com"

[env.staging.vars]
NODE_ENV = "staging"
LOG_LEVEL = "info"
API_BASE_URL = "https://staging-api.khoaugment.com"
FRONTEND_URL = "https://staging.pos.khoaugment.com"

# Build configuration
[build]
command = "npm run build"
cwd = "backend"

[build.upload]
format = "service-worker"

# Rules for routing
[[rules]]
type = "ESModule"
globs = ["**/*.js", "**/*.mjs"]
fallthrough = true

# Observability
[observability]
enabled = true

# Placement
placement = { mode = "smart" }

# Limits
[limits]
cpu_ms = 50000
memory_mb = 128

# Cron Triggers
[[triggers.crons]]
cron = "0 0 * * *"
# Daily backup at midnight

[[triggers.crons]]
cron = "0 */6 * * *"
# Analytics aggregation every 6 hours

[[triggers.crons]]
cron = "*/15 * * * *"
# Health checks every 15 minutes

# Custom domains (to be configured)
# [route]
# pattern = "pos.khoaugment.com/*"
# zone_name = "khoaugment.com"

# [route]
# pattern = "api.khoaugment.com/*"
# zone_name = "khoaugment.com"