# Cloudflare Workers configuration for Vietnamese POS System
name = "vietnamese-pos-system"
main = "src/index.ts"
compatibility_date = "2024-07-14"
compatibility_flags = ["nodejs_compat"]

# Environment variables
[env.production.vars]
ENVIRONMENT = "production"
API_BASE_URL = "https://vietnamese-pos-system.your-domain.workers.dev"
DATABASE_URL = "your-d1-database-url"

[env.staging.vars]
ENVIRONMENT = "staging"
API_BASE_URL = "https://vietnamese-pos-system-staging.your-domain.workers.dev"

# D1 Database bindings
[[env.production.d1_databases]]
binding = "DB"
database_name = "vietnamese-pos-db"
database_id = "your-database-id"

[[env.staging.d1_databases]]
binding = "DB"
database_name = "vietnamese-pos-db-staging"
database_id = "your-staging-database-id"

# KV Storage bindings for caching
[[env.production.kv_namespaces]]
binding = "CACHE"
id = "your-kv-namespace-id"

[[env.staging.kv_namespaces]]
binding = "CACHE"
id = "your-staging-kv-namespace-id"

# R2 Storage for images and files
[[env.production.r2_buckets]]
binding = "STORAGE"
bucket_name = "vietnamese-pos-storage"

[[env.staging.r2_buckets]]
binding = "STORAGE"
bucket_name = "vietnamese-pos-storage-staging"

# Routes for custom domain
[[env.production.routes]]
pattern = "pos.your-domain.com/*"
zone_name = "your-domain.com"

# Build configuration
[build]
command = "npm run build"
cwd = "."

# Node.js compatibility
node_compat = true

# Limits
[limits]
cpu_ms = 50000