# Production Cloudflare Workers Configuration for KhoAugment POS API
name = "kho1-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Worker configuration (disabled for free plan)
# [placement]
# mode = "smart"

# [limits]
# cpu_ms = 50

# Production environment variables
[env.production.vars]
ENVIRONMENT = "production"
API_VERSION = "v1"
BASE_URL = "https://kho1.pages.dev"
CORS_ORIGIN = "https://kho1.pages.dev"
RATE_LIMIT_REQUESTS = "1000"
RATE_LIMIT_WINDOW = "3600"
SESSION_TIMEOUT = "86400"
JWT_EXPIRE_TIME = "7d"
REFRESH_TOKEN_EXPIRE_TIME = "30d"
BCRYPT_ROUNDS = "12"
ADMIN_EMAIL = "admin@khoaugment.com"
JWT_SECRET = "kho1-production-jwt-secret-2025"
REFRESH_SECRET = "kho1-production-refresh-secret-2025"

# Development environment variables  
[env.development.vars]
ENVIRONMENT = "development"
API_VERSION = "v1"
BASE_URL = "http://localhost:3000"
CORS_ORIGIN = "http://localhost:3000,http://127.0.0.1:3000"
RATE_LIMIT_REQUESTS = "10000"
RATE_LIMIT_WINDOW = "3600"
SESSION_TIMEOUT = "86400"
JWT_EXPIRE_TIME = "1d"
REFRESH_TOKEN_EXPIRE_TIME = "7d"
BCRYPT_ROUNDS = "10"
ADMIN_EMAIL = "admin@localhost"

# Default environment variables
[vars]
ENVIRONMENT = "development"
API_VERSION = "v1"
BASE_URL = "http://localhost:3000"
CORS_ORIGIN = "http://localhost:3000"

# Production D1 Database
[[env.production.d1_databases]]
binding = "DB"
database_name = "kho1-production"
database_id = "39657891-9d7b-4a02-8b43-9921eb8c7d8e"

# Development D1 Database  
[[env.development.d1_databases]]
binding = "DB"
database_name = "kho1-development"
database_id = "39657891-9d7b-4a02-8b43-9921eb8c7d8e"

# Production R2 Storage for file uploads (disabled - R2 not enabled)
# [[env.production.r2_buckets]]
# binding = "STORAGE"
# bucket_name = "kho1-storage-production"

# Development R2 Storage
# [[env.development.r2_buckets]]
# binding = "STORAGE"
# bucket_name = "kho1-storage-development"

# Production KV Cache
[[env.production.kv_namespaces]]
binding = "CACHE"
id = "46b31b2c6ca449aaa3114d0ebb4fe645"

# Development KV Cache
[[env.development.kv_namespaces]]
binding = "CACHE"
id = "46b31b2c6ca449aaa3114d0ebb4fe645"

# Production Analytics Engine (disabled for now)
# [[env.production.analytics_engine_datasets]]
# binding = "ANALYTICS"
# dataset = "kho1_analytics_production"

# Development Analytics Engine
# [[env.development.analytics_engine_datasets]]
# binding = "ANALYTICS"
# dataset = "kho1_analytics_development"

# Default bindings for local development
[[d1_databases]]
binding = "DB"
database_name = "kho1-development"
database_id = "39657891-9d7b-4a02-8b43-9921eb8c7d8e"

# [[r2_buckets]]
# binding = "STORAGE"
# bucket_name = "kho1-storage-development"

[[kv_namespaces]]
binding = "CACHE"
id = "46b31b2c6ca449aaa3114d0ebb4fe645"

# Service bindings for microservices (disabled for now)
# [[env.production.services]]
# binding = "AUTH_SERVICE"
# service = "kho1-auth-service"

# [[env.production.services]]
# binding = "PAYMENT_SERVICE"
# service = "kho1-payment-service"

# Cron triggers for scheduled tasks (disabled for free plan)
# [[triggers.crons]]
# cron = "0 2 * * *"
# name = "daily-cleanup"

# [[triggers.crons]]
# cron = "*/15 * * * *"
# name = "sync-offline-orders"

# [[triggers.crons]]
# cron = "0 */6 * * *"
# name = "backup-database"

# Build configuration (disabled for quick deployment)
# [build]
# command = "npm run build"
# cwd = "."
# watch_dir = "src"

# Note: Miniflare configuration removed due to wrangler compatibility
