# Production Cloudflare Pages Configuration for KhoAugment POS
# Real deployment configuration for live production environment

[build]
command = "npm run build"
publish = "dist"
root_dir = "frontend"

[build.environment]
NODE_VERSION = "20"
NPM_VERSION = "10"
SKIP_DEPENDENCY_INSTALL = false

# Production environment variables
[env.production.vars]
VITE_API_URL = "https://kho1-api.bangachieu2.workers.dev"
VITE_APP_ENV = "production"
VITE_APP_NAME = "KhoAugment POS"
VITE_APP_VERSION = "1.0.0"
VITE_CLOUDFLARE_ACCOUNT_ID = "$CLOUDFLARE_ACCOUNT_ID"
VITE_BASE_URL = "https://kho1.pages.dev"
VITE_CDN_URL = "https://imagedelivery.net/your-account-hash"
VITE_VNPAY_RETURN_URL = "https://kho1.pages.dev/payment/vnpay/return"
VITE_MOMO_RETURN_URL = "https://kho1.pages.dev/payment/momo/return"
VITE_ZALOPAY_RETURN_URL = "https://kho1.pages.dev/payment/zalopay/return"
VITE_ENABLE_PWA = "true"
VITE_ENABLE_ANALYTICS = "true"
VITE_ENABLE_ERROR_TRACKING = "true"
VITE_CACHE_VERSION = "v1"
VITE_OFFLINE_SUPPORT = "true"

[env.staging.vars]
VITE_API_URL = "https://api-staging.khoaugment.com"
VITE_APP_ENV = "staging"
VITE_CLOUDFLARE_ACCOUNT_ID = "your-staging-account-id"
VITE_VNPAY_MERCHANT_ID = "your-staging-vnpay-merchant-id"
VITE_MOMO_PARTNER_CODE = "your-staging-momo-partner-code"
VITE_ZALOPAY_APP_ID = "your-staging-zalopay-app-id"
VITE_SENTRY_DSN = "your-staging-sentry-dsn"
VITE_VAPID_PUBLIC_KEY = "your-staging-vapid-public-key"

[env.development.vars]
VITE_API_URL = "http://localhost:8787"
VITE_APP_ENV = "development"
VITE_CLOUDFLARE_ACCOUNT_ID = "your-dev-account-id"
VITE_VNPAY_MERCHANT_ID = "your-dev-vnpay-merchant-id"
VITE_MOMO_PARTNER_CODE = "your-dev-momo-partner-code"
VITE_ZALOPAY_APP_ID = "your-dev-zalopay-app-id"
VITE_VAPID_PUBLIC_KEY = "your-dev-vapid-public-key"

# Production Security Headers
[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
X-XSS-Protection = "1; mode=block"
Referrer-Policy = "strict-origin-when-cross-origin"
Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
Permissions-Policy = "camera=(self), microphone=(), geolocation=(self), payment=(self), usb=(), bluetooth=(), accelerometer=(), gyroscope=(), magnetometer=(), ambient-light-sensor=(), autoplay=()"
Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://unpkg.com https://cdn.jsdelivr.net https://www.google-analytics.com https://www.googletagmanager.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdn.jsdelivr.net; font-src 'self' https://fonts.gstatic.com https://cdn.jsdelivr.net; img-src 'self' data: blob: https: https://imagedelivery.net; connect-src 'self' https://kho1-api.bangachieu2.workers.dev https://sandbox.vnpayment.vn https://vnpayment.vn https://test-payment.momo.vn https://payment.momo.vn https://sb-openapi.zalopay.vn https://openapi.zalopay.vn https://www.google-analytics.com; worker-src 'self' blob:; media-src 'self' blob:; frame-src 'none'; object-src 'none'; base-uri 'self'; form-action 'self' https://sandbox.vnpayment.vn https://vnpayment.vn;"

# Cache static assets
[[headers]]
for = "/assets/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/icons/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "*.js"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "*.css"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

# PWA files
[[headers]]
for = "/manifest.json"
[headers.values]
Cache-Control = "public, max-age=86400"
Content-Type = "application/manifest+json"

[[headers]]
for = "/sw.js"
[headers.values]
Cache-Control = "public, max-age=0, must-revalidate"
Content-Type = "application/javascript"

# API proxy headers
[[headers]]
for = "/api/*"
[headers.values]
Access-Control-Allow-Origin = "*"
Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With"
Access-Control-Max-Age = "86400"

# Redirects for SPA routing
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
conditions = {Country = ["VN"]}

# API redirects to Workers
[[redirects]]
from = "/api/*"
to = "https://khoaugment-pos-api-production.bangachieu2.workers.dev/:splat"
status = 200
force = true

# Legacy redirects
[[redirects]]
from = "/admin/*"
to = "/:splat"
status = 301

[[redirects]]
from = "/dashboard/*"
to = "/:splat"
status = 301

# Error pages
[[redirects]]
from = "/404"
to = "/index.html"
status = 200

[[redirects]]
from = "/500"
to = "/index.html"
status = 200

# Functions for edge computing
[functions]
directory = "functions"

# Build settings
[build.processing]
css = true
js = true
html = true
images = true

[build.processing.css]
minify = true

[build.processing.js]
minify = true

[build.processing.html]
minify = true

[build.processing.images]
format = "webp"
quality = 85

# Preview settings
[preview]
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Analytics
[analytics]
enabled = true

# Speed settings
[speed]
enabled = true

# Security settings
[security]
level = "high"

# Custom domains
[custom_domains]
production = ["khoaugment.com", "www.khoaugment.com"]
staging = ["staging.khoaugment.com"]

# Branch deployments
[branch_deployments]
enabled = true
preview_branch = "develop"

# Build notifications
[notifications]
email = ["admin@khoaugment.com"]
slack = "your-slack-webhook-url"

# Performance settings
[performance]
bundle_analyzer = true
lighthouse = true
web_vitals = true
