name: Deploy KhoAugment POS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare
    
    env:
      NODE_VERSION: '20'
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      
      - name: Install dependencies
        run: |
          npm ci
          npm run install:frontend
          npm run install:backend
      
      - name: Check security and quality
        run: |
          cd frontend && npm run lint
          cd ../backend && npm run lint
          cd .. && npm run build
      
      - name: Install Wrangler
        run: npm install -g wrangler
      
      - name: Deploy backend to Cloudflare Workers
        run: |
          cd backend
          wrangler deploy --env production
      
      - name: Deploy frontend to Cloudflare Pages
        run: |
          cd frontend
          npm run build
          wrangler pages deploy dist --project-name=kho1 --env production
      
      - name: Run post-deployment checks
        run: |
          echo "Checking API endpoint..."
          curl -s -o /dev/null -w "%{http_code}" https://kho1-api.bangachieu2.workers.dev/health || true
          echo "Checking frontend..."
          curl -s -o /dev/null -w "%{http_code}" https://kho1.pages.dev || true
      
      - name: Notify deployment success
        if: success()
        run: |
          echo "🚀 Deployment completed successfully!"
          echo "Frontend: https://kho1.pages.dev"
          echo "API: https://kho1-api.bangachieu2.workers.dev"